"""phase1 initial schema

Revision ID: 69a1df545cdc
Revises: 
Create Date: 2026-09-28 22:55:48.185426

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '69a1df545cdc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sex', sa.String(length=16), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact', sa.String(length=128), nullable=True),
    sa.Column('emergency_phone', sa.String(length=32), nullable=True),
    sa.Column('dominant_hand', sa.String(length=16), nullable=False),
    sa.Column('affected_side', sa.String(length=16), nullable=False),
    sa.Column('diagnosis_date', sa.Date(), nullable=True),
    sa.Column('disease_duration_years', sa.Double(), nullable=True),
    sa.Column('current_stage', sa.String(length=64), nullable=True),
    sa.Column('current_medications', sa.Text(), nullable=True),
    sa.Column('last_medication_time', sa.DateTime(), nullable=True),
    sa.Column('medication_state', sa.String(length=16), nullable=False),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('comorbidities', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('surgery_history', sa.Text(), nullable=True),
    sa.Column('rehab_history', sa.Text(), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_hospital_number'), ['hospital_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_name'), ['name'], unique=False)

    op.create_table('staff_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_users_username'), ['username'], unique=True)

    op.create_table('assessment_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('session_type', sa.String(length=32), nullable=False),
    sa.Column('medication_state', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['staff_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_sessions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_sessions_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('staff_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_staff_user_id'), ['staff_user_id'], unique=False)

    op.create_table('baselines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('baseline_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baselines_baseline_type'), ['baseline_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_baselines_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_baselines_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_baselines_patient_id'), ['patient_id'], unique=False)

    op.create_table('pose_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_type', sa.String(length=48), nullable=False),
    sa.Column('difficulty_json', sa.Text(), nullable=True),
    sa.Column('completion_score', sa.Float(), nullable=True),
    sa.Column('range_of_motion', sa.Float(), nullable=True),
    sa.Column('symmetry_score', sa.Float(), nullable=True),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.Column('hold_time_sec', sa.Float(), nullable=True),
    sa.Column('repetition_count', sa.Integer(), nullable=True),
    sa.Column('movement_speed', sa.Float(), nullable=True),
    sa.Column('valid_pose_frame_ratio', sa.Float(), nullable=True),
    sa.Column('raw_metrics_json', sa.Text(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=64), nullable=True),
    sa.Column('exercise_definition_version', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pose_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pose_sessions_exercise_type'), ['exercise_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_pose_sessions_patient_id'), ['patient_id'], unique=False)

    op.create_table('training_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['staff_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_plans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_plans_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_plans_status'), ['status'], unique=False)

    op.create_table('functional_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_session_id', sa.String(length=36), nullable=True),
    sa.Column('test_type', sa.String(length=32), nullable=False),
    sa.Column('hand', sa.String(length=8), nullable=True),
    sa.Column('value_primary', sa.Float(), nullable=False),
    sa.Column('value_secondary', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('medication_state', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['assessment_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['staff_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('functional_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_functional_assessments_assessment_session_id'), ['assessment_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_functional_assessments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_functional_assessments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_functional_assessments_performed_at'), ['performed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_functional_assessments_test_type'), ['test_type'], unique=False)

    op.create_table('media_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_session_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['assessment_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_files_assessment_session_id'), ['assessment_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_type'), ['type'], unique=False)

    op.create_table('piano_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('training_plan_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('judgement_window_ms', sa.Integer(), nullable=False),
    sa.Column('sequence_length', sa.Integer(), nullable=False),
    sa.Column('note_density', sa.Float(), nullable=False),
    sa.Column('hand_mode', sa.String(length=16), nullable=False),
    sa.Column('weak_side_ratio', sa.Float(), nullable=False),
    sa.Column('finger_complexity', sa.Integer(), nullable=False),
    sa.Column('session_duration_sec', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('miss_rate', sa.Float(), nullable=True),
    sa.Column('mean_response_latency_ms', sa.Float(), nullable=True),
    sa.Column('median_response_latency_ms', sa.Float(), nullable=True),
    sa.Column('response_latency_cv', sa.Float(), nullable=True),
    sa.Column('mean_timing_error_ms', sa.Float(), nullable=True),
    sa.Column('median_timing_error_ms', sa.Float(), nullable=True),
    sa.Column('timing_mae_ms', sa.Float(), nullable=True),
    sa.Column('timing_error_cv', sa.Float(), nullable=True),
    sa.Column('early_press_rate', sa.Float(), nullable=True),
    sa.Column('late_press_rate', sa.Float(), nullable=True),
    sa.Column('left_mean_latency', sa.Float(), nullable=True),
    sa.Column('right_mean_latency', sa.Float(), nullable=True),
    sa.Column('left_right_latency_difference', sa.Float(), nullable=True),
    sa.Column('left_accuracy', sa.Float(), nullable=True),
    sa.Column('right_accuracy', sa.Float(), nullable=True),
    sa.Column('weak_finger_error_rate', sa.Float(), nullable=True),
    sa.Column('sequence_completion_rate', sa.Float(), nullable=True),
    sa.Column('session_completion_rate', sa.Float(), nullable=True),
    sa.Column('difficulty_before_json', sa.Text(), nullable=True),
    sa.Column('difficulty_after_json', sa.Text(), nullable=True),
    sa.Column('adaptation_reason_json', sa.Text(), nullable=True),
    sa.Column('difficulty_engine_version', sa.String(length=64), nullable=True),
    sa.Column('metrics_version', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('piano_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_piano_sessions_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_piano_sessions_patient_id'), ['patient_id'], unique=False)

    op.create_table('finger_tapping_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_session_id', sa.String(length=36), nullable=False),
    sa.Column('media_file_id', sa.String(length=36), nullable=True),
    sa.Column('hand', sa.String(length=8), nullable=False),
    sa.Column('tapping_frequency', sa.Float(), nullable=True),
    sa.Column('avg_amplitude', sa.Float(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('avg_cycle_duration', sa.Float(), nullable=True),
    sa.Column('amplitude_cv', sa.Float(), nullable=True),
    sa.Column('speed_cv', sa.Float(), nullable=True),
    sa.Column('cycle_cv', sa.Float(), nullable=True),
    sa.Column('amplitude_slope', sa.Float(), nullable=True),
    sa.Column('speed_slope', sa.Float(), nullable=True),
    sa.Column('cycle_slope', sa.Float(), nullable=True),
    sa.Column('interruptions', sa.Integer(), nullable=True),
    sa.Column('valid_frame_ratio', sa.Float(), nullable=True),
    sa.Column('avg_landmark_confidence', sa.Float(), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('severity_label', sa.String(length=64), nullable=True),
    sa.Column('analyzer_version', sa.String(length=64), nullable=True),
    sa.Column('feature_schema_version', sa.String(length=32), nullable=False),
    sa.Column('analysis_config_json', sa.Text(), nullable=True),
    sa.Column('quality_json', sa.Text(), nullable=True),
    sa.Column('raw_features_json', sa.Text(), nullable=True),
    sa.Column('raw_timeseries_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['assessment_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finger_tapping_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finger_tapping_results_assessment_session_id'), ['assessment_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finger_tapping_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_finger_tapping_results_hand'), ['hand'], unique=False)

    op.create_table('micro_expression_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_session_id', sa.String(length=36), nullable=False),
    sa.Column('media_file_id', sa.String(length=36), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('feature_schema_version', sa.String(length=32), nullable=False),
    sa.Column('predicted_class', sa.String(length=64), nullable=True),
    sa.Column('pd_probability', sa.Float(), nullable=True),
    sa.Column('dominant_tag', sa.String(length=64), nullable=True),
    sa.Column('tag_distribution_json', sa.Text(), nullable=True),
    sa.Column('raw_output_json', sa.Text(), nullable=True),
    sa.Column('inference_time_ms', sa.Integer(), nullable=True),
    sa.Column('quality_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['assessment_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('micro_expression_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_micro_expression_results_assessment_session_id'), ['assessment_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_micro_expression_results_created_at'), ['created_at'], unique=False)

    op.create_table('piano_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('event_index', sa.Integer(), nullable=False),
    sa.Column('cue_onset_time_ms', sa.Integer(), nullable=True),
    sa.Column('target_time_ms', sa.Integer(), nullable=True),
    sa.Column('actual_time_ms', sa.Integer(), nullable=True),
    sa.Column('response_latency_ms', sa.Integer(), nullable=True),
    sa.Column('timing_error_ms', sa.Integer(), nullable=True),
    sa.Column('key_code', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=16), nullable=True),
    sa.Column('hand', sa.String(length=8), nullable=True),
    sa.Column('finger_hint', sa.String(length=16), nullable=True),
    sa.Column('key_down_time_ms', sa.Integer(), nullable=True),
    sa.Column('key_up_time_ms', sa.Integer(), nullable=True),
    sa.Column('hold_duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('is_missed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['piano_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('piano_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_piano_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_piano_events_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piano_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_piano_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_piano_events_created_at'))

    op.drop_table('piano_events')
    with op.batch_alter_table('micro_expression_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_micro_expression_results_created_at'))
        batch_op.drop_index(batch_op.f('ix_micro_expression_results_assessment_session_id'))

    op.drop_table('micro_expression_results')
    with op.batch_alter_table('finger_tapping_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finger_tapping_results_hand'))
        batch_op.drop_index(batch_op.f('ix_finger_tapping_results_created_at'))
        batch_op.drop_index(batch_op.f('ix_finger_tapping_results_assessment_session_id'))

    op.drop_table('finger_tapping_results')
    with op.batch_alter_table('piano_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_piano_sessions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_piano_sessions_mode'))

    op.drop_table('piano_sessions')
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_files_type'))
        batch_op.drop_index(batch_op.f('ix_media_files_sha256'))
        batch_op.drop_index(batch_op.f('ix_media_files_patient_id'))
        batch_op.drop_index(batch_op.f('ix_media_files_created_at'))
        batch_op.drop_index(batch_op.f('ix_media_files_assessment_session_id'))

    op.drop_table('media_files')
    with op.batch_alter_table('functional_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_functional_assessments_test_type'))
        batch_op.drop_index(batch_op.f('ix_functional_assessments_performed_at'))
        batch_op.drop_index(batch_op.f('ix_functional_assessments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_functional_assessments_created_at'))
        batch_op.drop_index(batch_op.f('ix_functional_assessments_assessment_session_id'))

    op.drop_table('functional_assessments')
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_plans_status'))
        batch_op.drop_index(batch_op.f('ix_training_plans_patient_id'))
        batch_op.drop_index(batch_op.f('ix_training_plans_created_at'))

    op.drop_table('training_plans')
    with op.batch_alter_table('pose_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pose_sessions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_pose_sessions_exercise_type'))

    op.drop_table('pose_sessions')
    with op.batch_alter_table('baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baselines_patient_id'))
        batch_op.drop_index(batch_op.f('ix_baselines_is_active'))
        batch_op.drop_index(batch_op.f('ix_baselines_created_at'))
        batch_op.drop_index(batch_op.f('ix_baselines_baseline_type'))

    op.drop_table('baselines')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_staff_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_assessment_sessions_patient_id'))

    op.drop_table('assessment_sessions')
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_users_username'))

    op.drop_table('staff_users')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_name'))
        batch_op.drop_index(batch_op.f('ix_patients_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_patients_hospital_number'))

    op.drop_table('patients')
    # ### end Alembic commands ###
